site_name: ansible管理windows
pages:
- 首页: "index.md"  
- 环境搭建: 
  - ansible控制windows环境搭建: "manual/1.0/deploy_doc.md"
- 使用说明:
  - 使用手册: "manual/1.0/oper.md"
- 版本控制: 
  - 版本说明: "manual/version.md"
theme: readthedocs