---

##服务的状态控制及模式
- name: "change {{ service_name }} status"
  win_service: 
    name: "{{ service_name }}"
    state: "{{ service_status }}"  ## started,stopped,restarted,absent,paused

- name: "change {{ service_name }} start_mode"
  win_service: 
    name: "{{service_name}}"
    start_mode: "{{ service_mode }}"  ## auto,manual,disabled,delayed
  register: ser_info

- name: "query {{ service_name }} status and start mode"
  debug:
    msg: "now {{ service_name }} service status is {{ ser_info.state }} and start mode is {{ ser_info.start_mode }}"


